### ISSUE TITLE
Quotas in `containerMetrics` no longer have named indices

### ISSUE THREAD

**Issue by NoelLH** [cloudfoundry-community/firehose-plugin#1]
Hi! I've been asking for help on this [in CF Slack #loggregator](https://cloudfoundry.slack.com/archives/C02HCCXV5/p1500368943510405) today, and was advised the problem might be fixable by changing how this plugin gets its `sonde-go`. I don't understand the rest of the related stack too well just yet!

The issue is that previously, `cf app-nozzle my-app -f ContainerMetric` gave output where each event included a `containerMetric` object whose named keys included `memoryBytesQuota` and `diskBytesQuota`.

Now it seems like the same numbers are there inside `containerMetric`, but the keys are now just `6` and `7` - e.g. `containerMetric:<applicationId:"11.." ... 6:1073741824 7:2147483648 >`

This is the current behaviour after pulling the stable `cf-cli` to a brand new Ubuntu 16.04 LTS instance and running `cf install-plugin 'Firehose Plugin' -r CF-Community -f`.

**Comment by jtuchscherer** [comment]
@NoelLH 
Sorry for getting back to you so late. I just fixed this by creating a new build with the newer versions of `sonde-go`.

Here is the output of the new plugin:
```
origin:"rep" eventType:ContainerMetric timestamp:1511041998797379756 deployment:"[...]" job:"diego-cell" index:"f37a21b4-f37f-4b22-a78d-3f34a6d2311e" ip:"[...]" tags:<key:"bosh_environment" value:"[...]" > tags:<key:"source_id" value:"ebfa4f6e-ce05-475e-ab7d-86af10f23975" > containerMetric:<applicationId:"ebfa4f6e-ce05-475e-ab7d-86af10f23975" instanceIndex:0 cpuPercentage:0.21831380954449323 memoryBytes:389058560 diskBytes:181100544 memoryBytesQuota:1073741824 diskBytesQuota:1073741824 >
```

Once the [plugin repo](https://github.com/cloudfoundry/cli-plugin-repo) accepts my [PR](https://github.com/cloudfoundry/cli-plugin-repo/pull/185), you should be able to download the new plugin. You can also manually install the plugin from here: https://github.com/cloudfoundry-community/firehose-plugin/releases/tag/0.13.0

Let me know if that fixes your problem.

Thanks

**Comment by jtuchscherer** [comment]
The new version is now available at: 
https://plugins.cloudfoundry.org/

**Comment by NoelLH** [comment]
Thanks very much @jtuchscherer, that looks to be working as expected again now using the version now distributed through the plugin repo. :)
